[package]
name = "xat"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.1.4", features = ["derive"] }
calamine = { version = "0.19.1", features = ["dates"] }

